apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: calcul11
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calcul11
  template:
    metadata:
      labels:
        app: calcul11
    spec:
      containers:
      - image: moenes/calcul11:latest
        name: calcul11
      schedulerName: default-scheduler
      val: 2
