apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: calcul14
spec:
  replicas: 4
  selector:
    matchLabels:
      app: calcul14
  template:
    metadata:
      labels:
        app: calcul14
    spec:
      containers:
      - image: moenes/calcul14:latest
        name: calcul14
      schedulerName: default-scheduler
      val: 5
